// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

// ArtworkDetails
export const REQUEST_ARTWORK_BY_ID = 'REQUEST_ARTWORK_BY_ID';
export const RECEIVE_ARTWORK_BY_ID = 'RECEIVE_ARTWORK_BY_ID';
export const ERROR_ARTWORK_BY_ID = 'ERROR_ARTWORK_BY_ID';

export const REQUEST_SAVE_ARTWORK = 'REQUEST_SAVE_ARTWORK';
export const RECEIVE_SAVE_ARTWORK = 'RECEIVE_SAVE_ARTWORK';
export const ERROR_SAVE_ARTWORK = 'ERROR_SAVE_ARTWORK';

export const CLEAR_ARTWORK_DETAILS = 'CLEAR_ARTWORK_DETAILS';

// ArtworksList
export const REQUEST_ARTWORKS = 'REQUEST_ARTWORKS';
export const RECEIVE_ARTWORKS = 'RECEIVE_ARTWORKS';
export const ERROR_ARTWORKS = 'ERROR_ARTWORKS';
export const DELETE_ARTWORK_REQUEST = 'DELETE_ARTWORK_REQUEST';
export const DELETE_ARTWORK_SUCCESS = 'DELETE_ARTWORK_SUCCESS';
export const DELETE_ARTWORK_ERROR = 'DELETE_ARTWORK_ERROR';

// Artists
export const REQUEST_ARTISTS = 'REQUEST_ARTISTS';
export const RECEIVE_ARTISTS = 'RECEIVE_ARTISTS';
export const ERROR_ARTISTS = 'ERROR_ARTISTS';

export const CREATE_ARTIST_REQUEST = 'CREATE_ARTIST_REQUEST';
export const CREATE_ARTIST_SUCCESS = 'CREATE_ARTIST_SUCCESS';
export const CREATE_ARTIST_ERROR = 'CREATE_ARTIST_ERROR';
