// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

// Artworks
export const REQUEST_ARTWORK = 'REQUEST_ARTWORK';
export const RECEIVE_ARTWORK = 'RECEIVE_ARTWORK';
export const ERROR_ARTWORK = 'ERROR_ARTWORK';
export const REQUEST_ARTWORKS = 'REQUEST_ARTWORKS';
export const RECEIVE_ARTWORKS = 'RECEIVE_ARTWORKS';
export const ERROR_ARTWORKS = 'ERROR_ARTWORKS';
export const DELETE_ARTWORK = 'DELETE_ARTWORK';

// Artists
export const REQUEST_ARTISTS = 'REQUEST_ARTISTS';
export const RECEIVE_ARTISTS = 'RECEIVE_ARTISTS';
export const ERROR_ARTISTS = 'ERROR_ARTISTS';
